version: "2"
services:
  hubot-rocketchat:
    image: cusdeb/hubot-rocketchat:1.0.11-armhf
    network_mode: "host"
    environment:
    - ROCKETCHAT_URL=http://127.0.0.1:8006
    - ROCKETCHAT_ROOM=
    - LISTEN_ON_ALL_PUBLIC=true
    - ROCKETCHAT_USER=meeseeks
    - ROCKETCHAT_PASSWORD=pass
    - HUBOT_NAME=bot
    - REDIS_URL=redis://127.0.0.1:16379
    - EXTERNAL_SCRIPTS=hubot-help,hubot-pugme,hubot-youtube,hubot-thesimpsons,hubot-redis-brain,git:tenten0213/hubot-thecat
    volumes:
    - ./scripts:/home/hubot/scripts
  redis:
    image: cusdeb/redis:5.0-armhf
    network_mode: "host"
    environment:
    - REDIS_CONF_bind=127.0.0.1
    - REDIS_CONF_port=16379
    - REDIS_CONF_loglevel=notice
    volumes:
    - /srv/redis-dump:/dump

